import type { Achievement } from '../types';

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_chapter',
    title: 'First Page',
    description: 'Complete your first chapter',
    icon: '📖',
    category: 'reading',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 1,
  },
  {
    id: 'halfway_reader',
    title: 'Halfway Hero',
    description: 'Complete 25 chapters',
    icon: '📚',
    category: 'reading',
    unlocked: false,
    rarity: 'rare',
    progress: 0,
    target: 25,
  },
  {
    id: 'bookworm',
    title: 'Bookworm',
    description: 'Complete all 51 chapters',
    icon: '🎓',
    category: 'reading',
    unlocked: false,
    rarity: 'legendary',
    progress: 0,
    target: 51,
  },
  {
    id: 'reading_streak_7',
    title: 'Consistent Reader',
    description: 'Maintain a 7-day reading streak',
    icon: '🔥',
    category: 'streak',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 7,
  },
  {
    id: 'first_solve',
    title: 'Hello World',
    description: 'Solve your first LeetCode problem',
    icon: '💻',
    category: 'coding',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 1,
  },
  {
    id: 'ten_problems',
    title: 'Code Apprentice',
    description: 'Solve 10 problems',
    icon: '⚡',
    category: 'coding',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 10,
  },
  {
    id: 'fifty_problems',
    title: 'Algorithm Adept',
    description: 'Solve 50 problems',
    icon: '🏆',
    category: 'coding',
    unlocked: false,
    rarity: 'rare',
    progress: 0,
    target: 50,
  },
  {
    id: 'hard_solver',
    title: 'Hard Hitter',
    description: 'Solve 10 Hard problems',
    icon: '💎',
    category: 'coding',
    unlocked: false,
    rarity: 'epic',
    progress: 0,
    target: 10,
  },
  {
    id: 'sapling_starter',
    title: 'Sapling Starter',
    description: 'Complete your first focus session',
    icon: '🌱',
    category: 'focus',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 1,
  },
  {
    id: 'deep_work_monk',
    title: 'Deep Work Monk',
    description: 'Complete 25 focus sessions',
    icon: '🧘',
    category: 'focus',
    unlocked: false,
    rarity: 'rare',
    progress: 0,
    target: 25,
  },
  {
    id: 'forest_guardian',
    title: 'Forest Guardian',
    description: 'Complete 100 focus sessions',
    icon: '🌳',
    category: 'focus',
    unlocked: false,
    rarity: 'epic',
    progress: 0,
    target: 100,
  },
  {
    id: 'focus_machine',
    title: 'Focus Machine',
    description: 'Accumulate 50 hours of focus',
    icon: '🤖',
    category: 'focus',
    unlocked: false,
    rarity: 'epic',
    progress: 0,
    target: 3000, // 3000 minutes = 50 hours
  },
  {
    id: 'zen_master',
    title: 'Zen Master',
    description: 'Maintain a 30-day focus streak',
    icon: '☯️',
    category: 'streak',
    unlocked: false,
    rarity: 'legendary',
    progress: 0,
    target: 30,
  },
  {
    id: 'hundred_hour_club',
    title: '100 Hour Club',
    description: 'Accumulate 100 hours of focus',
    icon: '💯',
    category: 'focus',
    unlocked: false,
    rarity: 'legendary',
    progress: 0,
    target: 6000, // 6000 minutes = 100 hours
  },
  {
    id: 'comeback_grower',
    title: 'Comeback Grower',
    description: 'Return after a 3-day break and complete a session',
    icon: '🌿',
    category: 'focus',
    unlocked: false,
    rarity: 'rare',
    progress: 0,
    target: 1,
  },
  {
    id: 'coding_streak_7',
    title: 'Consistent Coder',
    description: 'Maintain a 7-day coding streak',
    icon: '🗓️',
    category: 'streak',
    unlocked: false,
    rarity: 'common',
    progress: 0,
    target: 7,
  },
  {
    id: 'coding_streak_30',
    title: 'Code Crusader',
    description: 'Maintain a 30-day coding streak',
    icon: '🚀',
    category: 'streak',
    unlocked: false,
    rarity: 'legendary',
    progress: 0,
    target: 30,
  },
];

export const BOOK_CHAPTERS = Array.from({ length: 51 }, (_, i) => ({
  id: i + 1,
  number: i + 1,
  title: `Chapter ${i + 1}`,
  status: 'not_started' as const,
  completed: false,
}));

export const LEETCODE_TOPICS = [
  'Array', 'String', 'Hash Table', 'Dynamic Programming', 'Math',
  'Sorting', 'Greedy', 'Depth-First Search', 'Binary Search', 'Breadth-First Search',
  'Tree', 'Matrix', 'Two Pointers', 'Bit Manipulation', 'Stack',
  'Heap (Priority Queue)', 'Graph', 'Sliding Window', 'Backtracking', 'Union Find',
  'Linked List', 'Monotonic Stack', 'Recursion', 'Divide and Conquer', 'Queue',
  'System Design', 'Database / SQL', 'Frontend Development', 'Backend Development',
  'DevOps / Infra', 'Machine Learning / AI', 'General Coding', 'API Design / Testing',
];

export const PRODUCTIVITY_QUOTES = [
  "The secret of getting ahead is getting started. — Mark Twain",
  "It's not about having time. It's about making time.",
  "Focus is the art of knowing what to ignore.",
  "Done is better than perfect. Ship it.",
  "Small daily improvements lead to staggering long-term results.",
  "Deep work is the superpower of the 21st century. — Cal Newport",
  "The most dangerous distractions are the ones you love.",
  "Every expert was once a beginner.",
];
